"""Safety numbers, reimplemented from Signal's published numeric-fingerprint scheme.

Each party's half: SHA-512 over (version || identity key || stable id), re-hashed with the
key 5,200 times in total; the first 30 bytes become six 5-digit chunks. Both halves are
joined in a fixed order (by user id) so both people see the same 60 digits.
The identity keys here are mock keys generated by the server (see README).
"""

import base64
import hashlib

from pydantic import BaseModel
from sqlalchemy.ext.asyncio import AsyncSession

from app.context import Ctx
from app.errors import AppError
from app.models import IdentityVerification, User

VERSION = b"\x00\x00"
ITERATIONS = 5200


def fingerprint_half(identity_key: bytes, stable_id: bytes, iterations: int = ITERATIONS) -> str:
    h = hashlib.sha512(VERSION + identity_key + stable_id).digest()
    for _ in range(iterations - 1):
        h = hashlib.sha512(h + identity_key).digest()
    return "".join(f"{int.from_bytes(h[i:i + 5], 'big') % 100000:05d}" for i in range(0, 30, 5))


def compute_safety_number(key_a: bytes, id_a: int, key_b: bytes, id_b: int) -> str:
    halves = sorted([(id_a, key_a), (id_b, key_b)])
    return "".join(fingerprint_half(key, str(uid).encode()) for uid, key in halves)


class SafetyNumberOut(BaseModel):
    digits: str
    qr_payload: str
    verified: bool
    changed: bool


def _key(user: User) -> bytes:
    return base64.b64decode(user.identity_key)


async def verification_state(session: AsyncSession, viewer_id: int, subject: User) -> tuple[bool, bool]:
    """(verified, changed): changed means I verified an older key than the one they have now."""
    snapshot = await session.get(IdentityVerification, (viewer_id, subject.id))
    if snapshot is None:
        return False, False
    matches = snapshot.verified_key == subject.identity_key
    return matches, not matches


async def get_subject(session: AsyncSession, user_id: int) -> User:
    subject = await session.get(User, user_id)
    if subject is None:
        raise AppError(404, "user_not_found", "User not found")
    return subject


async def safety_number(session: AsyncSession, me: User, subject: User) -> SafetyNumberOut:
    digits = compute_safety_number(_key(me), me.id, _key(subject), subject.id)
    verified, changed = await verification_state(session, me.id, subject)
    return SafetyNumberOut(digits=digits, qr_payload=f"v0:{digits}", verified=verified, changed=changed)


async def mark_verified(session: AsyncSession, ctx: Ctx, me: User, subject: User) -> None:
    existing = await session.get(IdentityVerification, (me.id, subject.id))
    if existing is None:
        session.add(
            IdentityVerification(
                verifier_id=me.id, subject_id=subject.id, verified_key=subject.identity_key, verified_at=ctx.clock.now()
            )
        )
    else:
        existing.verified_key = subject.identity_key
        existing.verified_at = ctx.clock.now()
    await session.commit()


async def clear_verification(session: AsyncSession, me: User, subject: User) -> None:
    existing = await session.get(IdentityVerification, (me.id, subject.id))
    if existing is not None:
        await session.delete(existing)
        await session.commit()
