"""Demo world. Times are relative to boot so the app always looks freshly used."""

# key, phone, display name, username, about
USERS = [
    ("alice", "+15550100001", "Alice Chen", "alice.01", "Product designer · coffee first"),
    ("bob", "+15550100002", "Bob Martinez", "bob.02", "Trail runner"),
    ("priya", "+15550100003", "Priya Sharma", "priya.03", "Building things that matter"),
    ("daniel", "+15550100004", "Daniel Kim", "daniel.04", "Eng lead @ Phoenix"),
    ("emma", "+15550100005", "Emma Wilson", "emma.05", "Mom of two, plant collector"),
    ("lucas", "+15550100006", "Lucas Silva", "lucas.06", None),
    ("mei", "+15550100007", "Mei Tanaka", "mei.07", "📷 film photography"),
    ("jordan", "+15550100008", "Jordan Blake", "jordan.08", None),
]

# Mutual contacts among the first seven users; Jordan is a stranger to everyone.
CONTACT_PAIRS = [
    ("alice", "bob"), ("alice", "priya"), ("alice", "daniel"), ("alice", "emma"), ("alice", "lucas"),
    ("alice", "mei"), ("bob", "priya"), ("bob", "lucas"), ("bob", "daniel"), ("priya", "daniel"),
    ("priya", "mei"), ("emma", "mei"), ("daniel", "mei"),
]

DIRECTS = {
    "alice_bob": ("alice", "bob"),
    "alice_priya": ("alice", "priya"),
    "alice_daniel": ("alice", "daniel"),
    "alice_emma": ("alice", "emma"),
    "bob_priya": ("bob", "priya"),
    "alice_self": ("alice", "alice"),
}

# key: (title, description, admins, members)
GROUPS = {
    "hike": ("Weekend Hike", "Saturday trails & snacks 🥾", ["alice"], ["bob", "priya", "lucas"]),
    "family": ("Family", None, ["emma"], ["alice", "mei"]),
    "phoenix": ("Project Phoenix", "Launch coordination — v2 ships Friday", ["daniel", "alice"], ["bob", "priya", "mei"]),
}

# Conversation scripts: (minutes ago of the first line, [(sender, minutes after previous line, text[, media])]).
# Optional media: {"images": [names]} or {"file": "name.pdf"} — generated at seed time (app/seed/media.py).
SCRIPTS: dict[str, tuple[float, list[tuple]]] = {
    "alice_bob": (1940, [
        ("bob", 0, "Hey! Are you still up for the hike on Saturday?"),
        ("alice", 3, "Definitely. Which trail are we doing?"),
        ("bob", 2, "Thinking Eagle Peak. About 9 miles round trip"),
        ("alice", 1, "Oof, that's a big one. I'm in though"),
        ("bob", 4, "We can take it slow, the view at the top is worth it"),
        ("alice", 2, "Should I bring the camping stove? Coffee at the summit?"),
        ("bob", 1, "YES. That would be amazing ☕"),
        ("alice", 30, "Also, did you finish that book I lent you?"),
        ("bob", 45, "Halfway! The plot twist in chapter 12 got me"),
        ("alice", 2, "No spoilers but it gets even better"),
        ("bob", 600, "Morning! Weather looks perfect for Saturday"),
        ("alice", 15, "Sunny and 68°, can't ask for better"),
        ("bob", 3, "I'll pick you up at 7?"),
        ("alice", 5, "7 works. I'll have snacks ready"),
        ("bob", 1, "Trail mix with the chocolate bits please 😄"),
        ("alice", 1, "Obviously"),
        ("bob", 900, "Just bought new boots, hope they're broken in by then"),
        ("alice", 4, "Wear them around the house tonight, helps a lot"),
        ("bob", 2, "Good tip, doing that now"),
        ("alice", 300, "Can you send me the trail map when you get a sec?"),
        ("bob", 6, "Sure, sending it in the group too"),
        ("alice", 1, "Thanks! See you Saturday 🙌"),
    ]),
    "alice_priya": (3760, [
        ("priya", 0, "Alice!! Congrats on the promotion 🎉"),
        ("alice", 5, "Thank you so much! Still sinking in"),
        ("priya", 2, "Well deserved. Dinner to celebrate?"),
        ("alice", 3, "Yes please. Thursday?"),
        ("priya", 1, "Thursday works. That new Thai place on 5th?"),
        ("alice", 2, "Perfect, I've been wanting to try it"),
        ("priya", 1, "Booking for 7:30"),
        ("alice", 1200, "That was such a good dinner"),
        ("priya", 10, "The mango sticky rice!!"),
        ("alice", 2, "I'm still thinking about it"),
        ("priya", 1500, "Random question — do you still have that Figma template for onboarding flows?"),
        ("alice", 20, "I do, I'll share it with you tomorrow morning"),
        ("priya", 3, "Lifesaver 🙏"),
        ("alice", 400, "Shared it! Let me know if the components don't load"),
        ("priya", 30, "Got it, everything loads fine"),
        ("priya", 2, "The auto-layout setup is so clean"),
        ("alice", 3, "Took me a weekend to get right haha"),
        ("priya", 200, "Are you going to the design meetup next week?"),
        ("alice", 15, "Thinking about it. Who's speaking?"),
        ("priya", 2, "Someone from the Material team, talking about motion"),
        ("alice", 1, "Ooh, then yes"),
        ("priya", 1, "I'll grab us tickets"),
        ("alice", 1, "You're the best 💜"),
        ("priya", 150, "Tickets done! Tuesday 6pm"),
        ("alice", 10, "Calendar'd"),
        ("priya", 90, "Also my sister says hi, she loved your portfolio"),
        ("alice", 5, "Aw that's so nice, say hi back!"),
        ("priya", 60, "Will do. Are you free for a call later? Want feedback on my deck"),
        ("alice", 8, "After 5 works"),
        ("priya", 1, "Perfect, I'll ping you"),
    ]),
    "alice_daniel": (1250, [
        ("daniel", 0, "Do you have 15 min today to go over the release checklist?"),
        ("alice", 8, "Sure, 3pm?"),
        ("daniel", 1, "3pm works"),
        ("alice", 120, "Thanks for walking me through it"),
        ("daniel", 4, "Np. Can you review the onboarding copy before Thursday?"),
        ("alice", 2, "On it"),
        ("daniel", 1100, "Quick heads-up: QA found an issue with the share sheet on Android"),
        ("daniel", 1, "Not a blocker but we should look at it before the launch"),
        ("daniel", 2, "Can you take a look when you're in?"),
    ]),
    "alice_emma": (4800, [
        ("emma", 0, "Are you coming for dinner on Sunday? Mom is making lasagna"),
        ("alice", 30, "Wouldn't miss it! What should I bring?"),
        ("emma", 5, "Maybe dessert? The kids loved your brownies last time"),
        ("alice", 2, "Brownies it is 🍫"),
        ("emma", 2000, "The kids keep asking when Aunt Alice is visiting again"),
        ("alice", 60, "Tell them soon! I'll bring the board game"),
        ("emma", 3, "They'll be thrilled"),
        ("alice", 2500, "Here's that plant care guide I mentioned"),
        ("emma", 40, "Thank you! My fiddle leaf fig needs all the help it can get"),
        ("alice", 2, "Bright indirect light and don't overwater 🌿"),
    ]),
    "bob_priya": (2800, [
        ("bob", 0, "Priya, are you joining the hike this weekend?"),
        ("priya", 12, "Trying to! Depends on whether I finish my deck"),
        ("bob", 2, "Do it Friday night, come hike Saturday 😄"),
        ("priya", 3, "Wise words"),
        ("bob", 1600, "Final answer?"),
        ("priya", 8, "I'm in!"),
        ("bob", 1, "🙌"),
        ("priya", 120, "What snacks are people bringing?"),
        ("bob", 5, "Alice has trail mix covered, I'm bringing sandwiches"),
        ("priya", 2, "I'll make energy balls then"),
        ("bob", 1, "Legend"),
        ("priya", 300, "Do I need proper hiking boots or are trail runners ok?"),
        ("bob", 4, "Trail runners are fine if they have good grip"),
        ("priya", 1, "Cool, mine should be ok"),
        ("bob", 200, "Also bring a rain jacket just in case"),
        ("priya", 3, "Noted 👍"),
        ("priya", 500, "How was the load test btw?"),
        ("bob", 10, "Really good! p95 under 200ms"),
        ("priya", 2, "That's huge, nice work"),
        ("bob", 1, "Thanks! Team effort"),
    ]),
    "alice_self": (600, [
        ("alice", 0, "Pack list: headlamp, water filter, blister kit, extra socks"),
        ("alice", 120, "Ideas for the Phoenix launch post: lead with the speed improvements"),
        ("alice", 400, "Call the dentist Monday"),
    ]),
    "hike": (1340, [
        ("alice", 0, "Welcome to the hiking crew! 🥾"),
        ("bob", 5, "Let's gooo"),
        ("lucas", 3, "Thanks for adding me. What's the plan?"),
        ("alice", 2, "Eagle Peak this Saturday, meet at the trailhead at 7:30"),
        ("priya", 10, "Is there parking at the trailhead?"),
        ("bob", 2, "Small lot, so let's carpool"),
        ("lucas", 4, "I can drive, I have room for 3"),
        ("alice", 1, "Amazing, Priya and I can ride with you"),
        ("priya", 3, "Perfect 👍"),
        ("bob", 300, "Here's the trail map: 9.2 mi, 2,800 ft gain", {"images": ["trail-map", "summit", "lake"]}),
        ("lucas", 5, "That's a workout 😅"),
        ("alice", 2, "We'll take breaks. Summit coffee is the reward"),
        ("priya", 1, "Wait there's coffee?"),
        ("alice", 1, "I'm bringing the stove ☕"),
        ("priya", 1, "Best. Hike. Ever."),
        ("bob", 600, "Forecast still looks great for Saturday"),
        ("lucas", 20, "Should we bring bear spray?"),
        ("bob", 3, "Couldn't hurt, there were sightings last month"),
        ("lucas", 1, "I'll grab some"),
        ("priya", 200, "Anyone have an extra pair of trekking poles?"),
        ("alice", 15, "I have two pairs, you can borrow one"),
        ("priya", 1, "You're the best"),
        ("bob", 100, "Reminder: bring layers, it's windy at the top"),
        ("lucas", 30, "Leaving my place at 6:45 to pick you both up"),
        ("alice", 2, "See you then!"),
    ]),
    "family": (4700, [
        ("emma", 0, "Family group is officially created 😄"),
        ("mei", 10, "Hi everyone!"),
        ("alice", 3, "Finally haha"),
        ("emma", 2, "Sunday dinner at mom's, 6pm"),
        ("mei", 5, "I'll bring wine 🍷"),
        ("alice", 2, "Dessert is on me"),
        ("emma", 1600, "Photos from Sunday!", {"images": ["sunset"]}),
        ("mei", 3, "Aww these are so cute"),
        ("alice", 5, "The one with the kids and the dog 😂"),
        ("emma", 2, "Instant classic"),
        ("mei", 1800, "Does anyone know when grandma's birthday party is?"),
        ("emma", 30, "The 18th, at the lake house"),
        ("mei", 2, "Thanks! Adding it to the calendar"),
        ("alice", 60, "Should we all chip in for a gift?"),
        ("emma", 10, "Great idea. Maybe a photo album?"),
        ("mei", 3, "I can print some of my film shots for it 📷"),
        ("alice", 1, "That would be perfect"),
        ("emma", 2, "Love this family ❤️"),
        ("mei", 400, "I found a print shop that does photo books, should take a week"),
        ("emma", 20, "Perfect timing"),
        ("alice", 5, "Can I add a few of my photos too?"),
        ("mei", 2, "Of course! Send them over by Friday"),
        ("alice", 1, "Will do"),
        ("emma", 300, "Grandma called, she's so excited for the party"),
        ("mei", 4, "Did she guess anything about the gift?"),
        ("emma", 2, "Not a clue 🤫"),
        ("alice", 3, "Good, keep it that way haha"),
        ("mei", 200, "Who's driving up to the lake house?"),
        ("emma", 10, "We are, we have room for one more"),
        ("alice", 2, "I'll ride with you if that's ok"),
        ("emma", 1, "Of course!"),
        ("mei", 150, "I'll bring my camera for family photos"),
        ("emma", 5, "Yay, we haven't had a proper one in years"),
        ("alice", 2, "Matching sweaters? 😂"),
        ("mei", 1, "Absolutely not"),
        ("emma", 1, "Absolutely yes"),
    ]),
    "phoenix": (5800, [
        ("daniel", 0, "Kicking off the Phoenix v2 channel. Launch target: Friday"),
        ("bob", 10, "Backend is feature complete, finishing load tests"),
        ("priya", 5, "Analytics dashboards are ready for review"),
        ("mei", 3, "Marketing assets are in the shared drive. Launch plan attached", {"file": "Phoenix launch plan.pdf"}),
        ("alice", 8, "Final designs are in Figma, link in the doc"),
        ("daniel", 2, "Great progress team 🚀"),
        ("bob", 1400, "Load test results: p95 latency 180ms at 2x expected traffic"),
        ("daniel", 5, "That's excellent"),
        ("priya", 3, "Nice work Bob"),
        ("alice", 600, "Updated the onboarding screens based on usability feedback"),
        ("mei", 10, "They look so much cleaner now"),
        ("daniel", 4, "Agreed, the new empty states are great"),
        ("priya", 1500, "Heads up: found a tracking bug on the signup event"),
        ("bob", 20, "On it, should be a quick fix"),
        ("bob", 45, "Fixed and deployed to staging"),
        ("priya", 10, "Verified ✅"),
        ("daniel", 900, "Go/no-go meeting tomorrow at 10am"),
        ("mei", 5, "I'll prepare the launch announcement draft"),
        ("alice", 3, "I'll have the release notes ready"),
        ("daniel", 1200, "We're GO for Friday 🎉"),
        ("bob", 2, "Let's do this"),
        ("mei", 3, "Announcement scheduled for 9am"),
        ("priya", 1, "Dashboards are live"),
        ("daniel", 4, "Alice, can you double-check the app store screenshots?"),
        ("bob", 5, "Also we need a final sign-off on the pricing page"),
        ("daniel", 2, "Thanks everyone, this team is amazing"),
    ]),
}
